# Generated by Django 4.2.23 on 2025-07-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('both', 'Both')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['teacher', 'student', 'both'])), name='users_role_valid'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_students', to='tutor.courses'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='student_id',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_courses', to='tutor.users'),
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='enrolled_courses', to='tutor.users'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher_id',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'both']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tutor.users'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_courses', to='tutor.courses'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='student_id',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_students', to='tutor.users'),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.CheckConstraint(check=models.Q(('rating__in', ['1', '2', '3', '4', '5'])), name='reviews_rating_valid'),
        ),
        migrations.AddConstraint(
            model_name='bookings',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'confirmed', 'cancelled'])), name='bookings_status_valid'),
        ),
    ]
