# Generated by Django 4.2.23 on 2025-07-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_bookings_courses_reviews_users_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookings',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'confirmed', 'cancelled'])), name='bookings_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.CheckConstraint(check=models.Q(('rating__in', ['1', '2', '3', '4', '5'])), name='reviews_rating_valid'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['teacher', 'student', 'both'])), name='users_role_valid'),
        ),
    ]
