# Generated by Django 4.2.23 on 2025-07-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_bookings_bookings_status_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='teacher_id',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'both']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tutor.users'),
        ),
    ]
