"""Initial migration with all models and proper FK constraints

Revision ID: 5e9373f4deac
Revises: 
Create Date: 2025-07-27 10:43:26.990985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9373f4deac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('students',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_students_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=False),
    sa.Column('certifications', sa.String(length=255), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('teaching_experience', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('blue_premium', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_teachers_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='fk_courses_teacher_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('merchant_trade_no', sa.String(length=20), nullable=False),
    sa.Column('ecpay_trade_no', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('trade_desc', sa.String(length=200), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_type_charge_fee', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('rtn_code', sa.String(length=10), nullable=True),
    sa.Column('rtn_msg', sa.String(length=200), nullable=True),
    sa.Column('auth_code', sa.String(length=20), nullable=True),
    sa.Column('card4no', sa.String(length=4), nullable=True),
    sa.Column('card6no', sa.String(length=6), nullable=True),
    sa.Column('gwsr', sa.String(length=20), nullable=True),
    sa.Column('process_date', sa.DateTime(), nullable=True),
    sa.Column('simulate_paid', sa.String(length=1), nullable=True),
    sa.Column('custom_field1', sa.String(length=50), nullable=True),
    sa.Column('custom_field2', sa.String(length=50), nullable=True),
    sa.Column('custom_field3', sa.String(length=50), nullable=True),
    sa.Column('custom_field4', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='fk_payments_teacher_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecpay_trade_no')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_merchant_trade_no'), ['merchant_trade_no'], unique=True)

    op.create_table('bookings',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_bookings_course_id'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_bookings_student_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_reviews_course_id'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_reviews_student_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('bookings')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_merchant_trade_no'))

    op.drop_table('payments')
    op.drop_table('courses')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('users')
    # ### end Alembic commands ###
